 on:
   push:
      branches:
        - main
 name: release-please
 jobs:
   release-please:
     runs-on: ubuntu-latest
     permissions:
       contents: write
       pull-requests: write
     steps:
       - uses: GoogleCloudPlatform/release-please-action@v5
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           release-type: simple
           package-name: openfoodfacts-events
